version: 2.1

executors:
    go:
        docker:
            - image: circleci/golang:1.11.6
              environment:
                  GO111MODULE: 'on'
                  TZ: Asia/Tokyo

commands:
    restore_module:
        steps:
            - restore_cache:
                  name: Restore go modules cache
                  keys:
                      - mod-{{ checksum "go.mod" }}

    save_module:
        steps:
            - save_cache:
                  name: Save go modules cache
                  key: mod-{{ checksum "go.mod" }}
                  paths:
                      - /go/pkg/mod/cache

    vendoring:
        steps:
            - run:
                  name: Vendoring
                  command: go mod download

    test:
        steps:
            - run:
                  name: Run test
                  command: go test -v

    calc-coverage:
        steps:
            - run:
                  name : Calc converage
                  command: go test ./... -covermode=count -coverprofile=c.out
            - run:
                  name : Export html report
                  command: mkdir -p ./test_results && go tool cover -html=c.out -o ./test_results/coverage.html

            - store_artifacts:
                path: ./test_results
                destination: prefix
jobs:
    build:
        executor: go
        steps:
            - checkout
            - restore_module
            - vendoring
            - save_module
            - test
            - calc-coverage
